import re

def clean_string(str_in):
    str_in = re.sub(u'\u0057\u0308','W',str_in)
    str_in = re.sub(u'\u0077\u0308','w',str_in)
    str_in = re.sub(u'\u1e84', 'W', str_in)
    str_in = re.sub(u'\u1e85', 'w', str_in)
    str_in = re.sub(u'\u0056\u0308', 'V', str_in)
    str_in = re.sub(u'\u0076\u0308', 'v', str_in)
    str_in = re.sub(u'\u00eb', 'e', str_in)
    str_in = re.sub(u'\u0065\u0308', 'e', str_in)
    str_in = re.sub(u'\u00cb', 'E', str_in)
    str_in = re.sub(u'\u0045\u0308', 'E', str_in)
    str_in = re.sub("=",'',str_in)
    str_in = re.sub(u'\u0055\u0308', 'Ü', str_in)
    str_in = re.sub(u'\u0075\u0308', 'ü', str_in)
    str_in = re.sub('\t','',str_in)
    str_in = re.sub(u'y\u0308','y',str_in)
    str_in = re.sub(u'\u00ff','y',str_in)
    str_in = re.sub(u'o\u0308', 'ö', str_in)
    str_in = re.sub(u'a\u0308', 'ä', str_in)
    str_in = re.sub('\+', '' ,str_in)
    str_in = re.sub('\?','',str_in)
    str_in = re.sub('\(','',str_in)
    str_in = re.sub('\)','',str_in)
    str_in = re.sub("[`']",'',str_in)
    str_in = re.sub('\$#[^\$#]*#\$','',str_in)
    str_in = re.sub('-\$','',str_in)
    str_in = re.sub('\$-','',str_in)
    str_in = re.sub('§\$', '', str_in)
    str_in = re.sub('\$§', '', str_in)
    str_in = re.sub('&','%',str_in)
    str_in = re.sub(u'\u00e5','ä',str_in)
    str_in = re.sub('ß','ſ',str_in)
    str_in = str_in.replace("\\","")
    str_in = str_in.replace("„","")
    str_in = str_in.replace("—","-")
    str_in = str_in.replace('–',"-")
    str_in = str_in.replace("ů","u")
    str_in = str_in.replace("!","")
    str_in = str_in.replace("_","")
    str_in = str_in.replace("‰","")
    str_in = str_in.replace(";","")
    str_in = str_in.replace("ê","")
    str_in = str_in.replace("⁓","-")
    str_in = str_in.replace("¬","-")
    str_in = str_in.replace("é","e")
    str_in = str_in.replace("°","")
    str_in = str_in.replace("#","")
    str_in = str_in.replace('̈',"")
    str_in = str_in.replace("$","")
    str_in = str_in.replace('|',"I")
    return str_in